version: '3'

services:
  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  database:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: trodo
      MYSQL_DATABASE: trodo_test
      MYSQL_USER: kristina
      MYSQL_PASSWORD: trodo
    ports:
      - 3306:3306
